apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: pushover-alerting
  namespace: monitoring
  labels:
    alertmanagerConfig: pushover-alerting
spec:
  route:
    groupBy: ["job"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 2h
    receiver: "pushover"
