apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-deployement
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: monitoring
        port: web
  serviceAccountName: prometheus-instance
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  ruleSelector: {}
  ruleNamespaceSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
