{
 "title": "PocketShorten",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "R/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pocketshorten_frontend_totalops[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pocketshorten_frontend_duration_seconds_bucket{}"
    }
   ]
  },
  {
   "title": "Requests by Status per minute",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pocketshorten_frontend_totalops[5m])) by (responsecode)"
    }
   ]
  },
  {
   "title": "Requests per instance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pocketshorten_frontend_totalops[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(pocketshorten_frontend_totalops{responsecode!=\"200\"}[5m])",
     "legendFormat": "{{ method }} : {{responsecode}}"
    }
   ]
  },
  {
   "title": "Latency percentiles",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pocketshorten_frontend_duration_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(pocketshorten_frontend_duration_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(pocketshorten_frontend_duration_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}