apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketshorten-real
commonLabels:
  app: pocketshorten-fe
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - metricsservice.yaml
secretGenerator:
  - name: db-user
    envs:
      - .env.creds
configMapGenerator:
  - name: psconfig
    literals:
      - URL=http://pb-service:8080
      - LOGLEVEL=debug
