apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketshorten-viper
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: pocketshorten-viper
          image: registry.hub.docker.com/clarkezone/pocketshorten:0.0.3
