apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketshorten-viper
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: pocketshorten-viper
          image: registry.hub.docker.com/clarkezone/pocketshorten:0.0.5
          livenessProbe:
            httpGet:
              path: /live
              port: 8090
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8090
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
