apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pocketshorterner-tunnelmetrics-servicemonitor
  labels:
    name: pocketshortener-tunnelmetrics-servicemonitor
  namespace: pocketshorten
spec:
  selector:
    matchLabels:
      app: pocketshorten-tunnel
  namespaceSelector:
    matchNames:
      - pocketshorten
  endpoints:
    - port: tunnelmetrics
