apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketshorten
commonLabels:
  app: pocketshorten-viper
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - metricsservice.yaml
  - servicemonitor.yaml
secretGenerator:
configMapGenerator:
  - name: vipconfig
    files:
      - pocketshorten.json
  - name: psconfig
    literals:
      - URL=http://pb-service:8080
      - LOGLEVEL=debug
      - CONFIG=/pocketshorten.json
