apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helloworld
  labels:
    app: nginx-helloworld
spec:
  selector:
    matchLabels:
      app: nginx-helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-helloworld
    spec:
      containers:
        - name: nginx-helloworld
          image: nginx:1.20-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: cfg-html3 #name of configmap below
      volumes:
        - name: cfg-html3
          configMap:
            name: html3 #from configmapgenerator name
