apiVersion: v1
data:
  index.html: |
    <html>
    <head>
    <title>James Clarke picture of wife</title>
    </head>
    <body>
    <h1>Hello Clarkezone!</h1>
    <p>This is the default environment which i can modify.</p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: index-simplehtml
