namespace: nginxsimple
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - tunnel_deployment.yaml

configMapGenerator:
  - name: html3
    files:
      - nginxconfig/html3.html #this is raw file
      - nginxconfig/html2.html #this is raw file
      - nginxconfig/html1.html #this is raw file
      - nginxconfig/index.html #this is raw file
      - nginxconfig/cheezburger.jpg
  - name: cloudflare-nginxsimplefile-configs
    files:
      - tunnelconfig/config.yaml
secretGenerator:
  - name: cloudflare-nginxsimplefile-cert
    files:
      - tunnelsecrets/cert.pem
  - name: cloudflare-nginxsimplefile-creds
    files:
      - secrets/TUNNEL_ID.json
