apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-helloworld
  name: nginx-helloworld
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30958
  selector:
    app: nginx-helloworld
  sessionAffinity: None
  type: NodePort
