namePrefix: prod-
namespace: pocketshorten
commonLabels:
  environment: production
bases:
  - ../../base
patchesStrategicMerge:
  - shortener_deployment.yaml
resources:
  - tunnel_deployment.yaml
  - tunnel_metricsservice.yaml
  - tunnel_monitor.yaml
  - tunnel_pdb.yaml
  - shortener_pdb.yaml
  - shortener_promAlertRule.yaml
secretGenerator:
  - name: cloudflare-pocketshorten-cert
    files:
      - tunnelsecrets/cert.pem
  - name: cloudflare-pocketshorten-creds
    files:
      - tunnelsecrets/TUNNEL_ID.json
configMapGenerator:
  - name: cloudflare-pocketshorten-configs
    files:
      - tunnelconfig/config.yaml
