apiVersion: apps/v1
kind: Deployment
metadata:
  name:
spec:
  template:
    spec:
      containers:
        - name: pocketshorten-viper
          resources:
            limits:
              memory: 512Mi
