apiVersion: v1
kind: Service
metadata:
  labels:
    app: pocketshorten-tunnel
  name: tunnel-metrics
spec:
  ports:
    - port: 2000
      name: tunnelmetrics
  selector:
    app: pocketshorten-tunnel
