apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  clusterIP: 10.43.131.231
  clusterIPs:
    - 10.43.131.231
  ports:
    - name: "http"
      port: 3000
      targetPort: "http"
