apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketshorten-backend
  labels:
    app: kustomize
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kustomize
    spec:
      containers:
        - name: pocketshorten-backend
          # image: registry.dev.clarkezone.dev/pocketgeotemp:latest
          image:
            registry.hub.docker.com/clarkezone/pocketshorten:main
            #        image: registry.hub.docker.com/clarkezone/previewd:webhooke2e
          args: ["testservergrpc"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
            - containerPort: 8095
          env:
            - name: LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-backend
                  key: LOGLEVEL
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
