apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketshorten-real
commonLabels:
  app: pocketshorten-be
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: config-backend
    literals:
      - URL=http://pb-service:8080
      - LOGLEVEL=debug
